"""initial schema

Revision ID: 136ae1bcba8b
Revises: 
Create Date: 2026-06-29 21:41:37.337356
"""
from alembic import op
import sqlalchemy as sa


revision = '136ae1bcba8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applied_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('vacancy_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('company', sa.String(length=512), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'site_id', 'vacancy_id', name='uq_applied_user_site_vacancy')
    )
    with op.batch_alter_table('applied_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applied_history_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_applied_user_site_date', ['user_id', 'site_id', 'applied_at'], unique=False)

    op.create_table('site_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'site_id', name='uq_siteconfig_user_site')
    )
    with op.batch_alter_table('site_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_configs_user_id'), ['user_id'], unique=False)

    op.create_table('site_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('username_enc', sa.String(length=512), nullable=False),
    sa.Column('password_enc', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'site_id', name='uq_sitecred_user_site')
    )
    with op.batch_alter_table('site_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('proxy_url_enc', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('site_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_credentials_user_id'))

    op.drop_table('site_credentials')
    with op.batch_alter_table('site_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_configs_user_id'))

    op.drop_table('site_configs')
    with op.batch_alter_table('applied_history', schema=None) as batch_op:
        batch_op.drop_index('ix_applied_user_site_date')
        batch_op.drop_index(batch_op.f('ix_applied_history_user_id'))

    op.drop_table('applied_history')
    # ### end Alembic commands ###
