"""add last_status to applied_history

Revision ID: e615229f2836
Revises: 136ae1bcba8b
Create Date: 2026-06-30 00:18:18.215153
"""
from alembic import op
import sqlalchemy as sa


revision = 'e615229f2836'
down_revision = '136ae1bcba8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applied_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_status', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applied_history', schema=None) as batch_op:
        batch_op.drop_column('last_status')

    # ### end Alembic commands ###
