"""add telegram_chat_id to users

Revision ID: 7d1627b7dd11
Revises: e615229f2836
Create Date: 2026-06-30 00:29:48.166926
"""
from alembic import op
import sqlalchemy as sa


revision = '7d1627b7dd11'
down_revision = 'e615229f2836'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telegram_chat_id')

    # ### end Alembic commands ###
